### ISSUE TITLE
Task 1: Preprocessing and data analysis

### ISSUE THREAD

**Issue by Max1412** [Max1412/ML-Assignment#1]
### Task 1: Preprocessing and data analysis
- [x] load the data
* [overview](https://www.kaggle.com/c/titanic/data)
- [x] study how the features look like (plotting)
- [ ] short summary
- [ ] expectations about prediction (which features might contribute)
[Example](https://www.kaggle.com/omarelgabry/titanic/a-journey-through-titanic/comments)
- [x] think about further preprocessing steps (e.g. 'handling categorial variables')
