### ISSUE TITLE
Task 2: Prediction

### ISSUE THREAD

**Issue by Max1412** [Max1412/ML-Assignment#2]
### Task 2: Prediction
Use the **skikit-learn** library and a **Decision Tree Classifier**.

- [x] Fit the classifier on training data
- [x] Predict survival on test data
- [x] Evaluate the classifier's performance appropriately (also think about things
like cross validation)
- [ ] Consider accuracy improvements (e.g., parameter tuning via grid search)
- [ ] Compare the performance to an appropriate baseline
- [x] Print the classifiers decision rules (or also visualize them) on the complete
data
- [ ] Interpret and discuss feature importance
