### ISSUE TITLE
Task 3: Implement your own Decision Tree Classifier

### ISSUE THREAD

**Issue by Max1412** [Max1412/ML-Assignment#3]
### Task 3: Implement your own Decision Tree Classifier
- [x] Implement a classifier as a Python class using the default scikit-learn API:
  - [x] **fit** and **predict** functions (at least)
  * [Documentation](http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator)
- [x] Implement at least two evaluation criterions
  - [x] gini impurity
  - [x] information gain
- [x] Use any decision tree algorithm [Overview and comparison](http://www.cs.uvm.edu/~icdm/algorithms/10Algorithms-08.pdf) and [Youtube Videos](https://www.youtube.com/watch?v=eKD5gxPPeY0)
  - [x] ID3
  * C4.5
  * CART
  * etc.
- [x] Fit the classifier on training data
- [x] Predict survival on test data
- [ ] Evaluate the classifier's performance **appropriately**
- [ ] Compare the results to those obtained by the scikit-learn implementation.
  - [ ] Check for discrepancies and consider the parameters of the scikit-learn
implementation to rule out certain differences.
  - [ ] In case of differences, try to elaborate on them.
- [x] Print the classifiers decision rules (or also visualize them) on the complete
data.
